# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.23.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.23.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mykhaylomarfeychuk/dev/gb-emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mykhaylomarfeychuk/dev/gb-emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.23.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.23.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mykhaylomarfeychuk/dev/gb-emulator/CMakeFiles /Users/mykhaylomarfeychuk/dev/gb-emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mykhaylomarfeychuk/dev/gb-emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameBoy

# Build rule for target.
GameBoy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameBoy
.PHONY : GameBoy

# fast build rule for target.
GameBoy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/build
.PHONY : GameBoy/fast

src/Cpu.o: src/Cpu.cpp.o
.PHONY : src/Cpu.o

# target to build an object file
src/Cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Cpu.cpp.o
.PHONY : src/Cpu.cpp.o

src/Cpu.i: src/Cpu.cpp.i
.PHONY : src/Cpu.i

# target to preprocess a source file
src/Cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Cpu.cpp.i
.PHONY : src/Cpu.cpp.i

src/Cpu.s: src/Cpu.cpp.s
.PHONY : src/Cpu.s

# target to generate assembly for a file
src/Cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Cpu.cpp.s
.PHONY : src/Cpu.cpp.s

src/Ext_Instructions.o: src/Ext_Instructions.cpp.o
.PHONY : src/Ext_Instructions.o

# target to build an object file
src/Ext_Instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Ext_Instructions.cpp.o
.PHONY : src/Ext_Instructions.cpp.o

src/Ext_Instructions.i: src/Ext_Instructions.cpp.i
.PHONY : src/Ext_Instructions.i

# target to preprocess a source file
src/Ext_Instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Ext_Instructions.cpp.i
.PHONY : src/Ext_Instructions.cpp.i

src/Ext_Instructions.s: src/Ext_Instructions.cpp.s
.PHONY : src/Ext_Instructions.s

# target to generate assembly for a file
src/Ext_Instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Ext_Instructions.cpp.s
.PHONY : src/Ext_Instructions.cpp.s

src/GB.o: src/GB.cpp.o
.PHONY : src/GB.o

# target to build an object file
src/GB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/GB.cpp.o
.PHONY : src/GB.cpp.o

src/GB.i: src/GB.cpp.i
.PHONY : src/GB.i

# target to preprocess a source file
src/GB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/GB.cpp.i
.PHONY : src/GB.cpp.i

src/GB.s: src/GB.cpp.s
.PHONY : src/GB.s

# target to generate assembly for a file
src/GB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/GB.cpp.s
.PHONY : src/GB.cpp.s

src/Gpu.o: src/Gpu.cpp.o
.PHONY : src/Gpu.o

# target to build an object file
src/Gpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Gpu.cpp.o
.PHONY : src/Gpu.cpp.o

src/Gpu.i: src/Gpu.cpp.i
.PHONY : src/Gpu.i

# target to preprocess a source file
src/Gpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Gpu.cpp.i
.PHONY : src/Gpu.cpp.i

src/Gpu.s: src/Gpu.cpp.s
.PHONY : src/Gpu.s

# target to generate assembly for a file
src/Gpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Gpu.cpp.s
.PHONY : src/Gpu.cpp.s

src/Instructions.o: src/Instructions.cpp.o
.PHONY : src/Instructions.o

# target to build an object file
src/Instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Instructions.cpp.o
.PHONY : src/Instructions.cpp.o

src/Instructions.i: src/Instructions.cpp.i
.PHONY : src/Instructions.i

# target to preprocess a source file
src/Instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Instructions.cpp.i
.PHONY : src/Instructions.cpp.i

src/Instructions.s: src/Instructions.cpp.s
.PHONY : src/Instructions.s

# target to generate assembly for a file
src/Instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Instructions.cpp.s
.PHONY : src/Instructions.cpp.s

src/Interrupt.o: src/Interrupt.cpp.o
.PHONY : src/Interrupt.o

# target to build an object file
src/Interrupt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Interrupt.cpp.o
.PHONY : src/Interrupt.cpp.o

src/Interrupt.i: src/Interrupt.cpp.i
.PHONY : src/Interrupt.i

# target to preprocess a source file
src/Interrupt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Interrupt.cpp.i
.PHONY : src/Interrupt.cpp.i

src/Interrupt.s: src/Interrupt.cpp.s
.PHONY : src/Interrupt.s

# target to generate assembly for a file
src/Interrupt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Interrupt.cpp.s
.PHONY : src/Interrupt.cpp.s

src/Registers.o: src/Registers.cpp.o
.PHONY : src/Registers.o

# target to build an object file
src/Registers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Registers.cpp.o
.PHONY : src/Registers.cpp.o

src/Registers.i: src/Registers.cpp.i
.PHONY : src/Registers.i

# target to preprocess a source file
src/Registers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Registers.cpp.i
.PHONY : src/Registers.cpp.i

src/Registers.s: src/Registers.cpp.s
.PHONY : src/Registers.s

# target to generate assembly for a file
src/Registers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Registers.cpp.s
.PHONY : src/Registers.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Timer.o: src/Timer.cpp.o
.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i
.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s
.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/joypad.o: src/joypad.cpp.o
.PHONY : src/joypad.o

# target to build an object file
src/joypad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/joypad.cpp.o
.PHONY : src/joypad.cpp.o

src/joypad.i: src/joypad.cpp.i
.PHONY : src/joypad.i

# target to preprocess a source file
src/joypad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/joypad.cpp.i
.PHONY : src/joypad.cpp.i

src/joypad.s: src/joypad.cpp.s
.PHONY : src/joypad.s

# target to generate assembly for a file
src/joypad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/joypad.cpp.s
.PHONY : src/joypad.cpp.s

src/mmu.o: src/mmu.cpp.o
.PHONY : src/mmu.o

# target to build an object file
src/mmu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/mmu.cpp.o
.PHONY : src/mmu.cpp.o

src/mmu.i: src/mmu.cpp.i
.PHONY : src/mmu.i

# target to preprocess a source file
src/mmu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/mmu.cpp.i
.PHONY : src/mmu.cpp.i

src/mmu.s: src/mmu.cpp.s
.PHONY : src/mmu.s

# target to generate assembly for a file
src/mmu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameBoy.dir/build.make CMakeFiles/GameBoy.dir/src/mmu.cpp.s
.PHONY : src/mmu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameBoy"
	@echo "... src/Cpu.o"
	@echo "... src/Cpu.i"
	@echo "... src/Cpu.s"
	@echo "... src/Ext_Instructions.o"
	@echo "... src/Ext_Instructions.i"
	@echo "... src/Ext_Instructions.s"
	@echo "... src/GB.o"
	@echo "... src/GB.i"
	@echo "... src/GB.s"
	@echo "... src/Gpu.o"
	@echo "... src/Gpu.i"
	@echo "... src/Gpu.s"
	@echo "... src/Instructions.o"
	@echo "... src/Instructions.i"
	@echo "... src/Instructions.s"
	@echo "... src/Interrupt.o"
	@echo "... src/Interrupt.i"
	@echo "... src/Interrupt.s"
	@echo "... src/Registers.o"
	@echo "... src/Registers.i"
	@echo "... src/Registers.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/joypad.o"
	@echo "... src/joypad.i"
	@echo "... src/joypad.s"
	@echo "... src/mmu.o"
	@echo "... src/mmu.i"
	@echo "... src/mmu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

